# this compose file is setup for dev/testing purposes
# you should figure something else out for actual deployments
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: fortunes
      POSTGRES_USER: fortunes
      POSTGRES_PASSWORD: fortunes
      PG_USER: fortunes
    ports:
      - 127.0.0.1::5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fortunes"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-migrations:
    image: amacneil/dbmate
    command: --wait --no-dump-schema -u postgres://fortunes:fortunes@postgres:5432/fortunes?sslmode=disable up 
    volumes:
      - ./db:/db:ro
    depends_on:
      postgres:
        condition: service_healthy

  # pgbouncer:
  #   image: bitnami/pgbouncer
  #   links:
  #     - postgres:postgres
  #   ports:
  #     - 127.0.0.1::6432
  #   environment:
  #     PGBOUNCER_DATABASE: fortunes
  #     POSTGRESQL_USERNAME: fortunes
  #     POSTGRESQL_PASSWORD: fortunes
  #     POSTGRESQL_HOST: postgres
  #     POSTGRESQL_PORT: 5432

